const projects=[
{id:1,title:'City After Dark',category:'Brand Film',duration:'00:45',client:'Lifestyle Campaign',description:'A fast-paced visual story built around movement, light, and urban energy.',image:'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1400&q=80'},
{id:2,title:'Crafted by Hand',category:'Product Story',duration:'01:10',client:'Artisan Showcase',description:'An intimate short film celebrating detail, process, and human craftsmanship.',image:'https://images.unsplash.com/photo-1452802447250-470a88ac82bc?auto=format&fit=crop&w=1400&q=80'},
{id:3,title:'Momentum',category:'Corporate Film',duration:'00:58',client:'Enterprise Campaign',description:'A polished business narrative designed for launches, events, and digital channels.',image:'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=80'},
{id:4,title:'A Quiet Morning',category:'Short Film',duration:'02:15',client:'Original Work',description:'A warm, observational piece where natural light carries the story.',image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=80'},
{id:5,title:'Built to Move',category:'Commercial',duration:'00:30',client:'Automotive Concept',description:'Cinematic product shots, bold sound design, and high-energy editing.',image:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=80'},
{id:6,title:'People of Tomorrow',category:'Documentary',duration:'01:35',client:'Social Impact Story',description:'A human-centered portrait shaped by authentic moments and honest voices.',image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1400&q=80'}];
const categories=['All',...new Set(projects.map(p=>p.category))];let active='All';
const grid=document.getElementById('projectGrid'),filters=document.getElementById('filters'),search=document.getElementById('searchInput'),modal=document.getElementById('modal'),modalContent=document.getElementById('modalContent');
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="filter ${c===active?'active':''}" data-filter="${c}">${c}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.filter;renderFilters();renderProjects()})}
function renderProjects(){const q=search.value.toLowerCase();const visible=projects.filter(p=>(active==='All'||p.category===active)&&`${p.title} ${p.category} ${p.client}`.toLowerCase().includes(q));grid.innerHTML=visible.length?visible.map(p=>`<button class="project-card" data-id="${p.id}"><div class="project-image"><img src="${p.image}" alt="${p.title}"><span class="duration">${p.duration}</span></div><div class="project-info"><span class="category">${p.category.toUpperCase()}</span><h3>${p.title}</h3><p>${p.client}</p></div></button>`).join(''):'<p class="empty">No matching projects found.</p>';grid.querySelectorAll('.project-card').forEach(card=>card.onclick=()=>openProject(Number(card.dataset.id)))}
function openModal(content){modalContent.innerHTML=content;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openProject(id){const p=projects.find(x=>x.id===id);openModal(`<img class="modal-media" src="${p.image}" alt="${p.title}"><p class="label">${p.category.toUpperCase()}</p><h2>${p.title}</h2><p class="section-copy">${p.description}</p><p class="section-copy">Replace this image with a YouTube, Vimeo, or hosted video embed.</p>`)}
function openForm(type){const register=type==='register';openModal(`<p class="label">${register?'VIEWER ACCESS':'BUSINESS ENQUIRY'}</p><h2>${register?'Register to view':'Request a business demo'}</h2><p class="section-copy">${register?'Create a viewer profile using your mobile number.':'Share a few details about your project.'}</p><form id="leadForm"><input required name="name" placeholder="Full name">${register?'':'<input required name="company" placeholder="Company or organization"><input required type="email" name="email" placeholder="Work email">'}<input required type="tel" name="mobile" inputmode="numeric" pattern="[0-9]{10}" placeholder="10-digit mobile number">${register?'':'<textarea required name="message" rows="4" placeholder="Tell me about your project"></textarea>'}<label class="consent"><input required type="checkbox">I agree to the privacy policy and consent to being contacted about this request.</label><button class="button gold" type="submit">${register?'Send OTP':'Submit demo request'}</button></form>`);document.getElementById('leadForm').onsubmit=e=>{e.preventDefault();modalContent.innerHTML=`<div class="success"><div class="success-mark">✓</div><h2>${register?'OTP requested':'Request received'}</h2><p class="section-copy">Demo mode only. Connect a backend, database and ${register?'SMS/OTP provider':'email or CRM service'} to receive real submissions.</p></div>`}}
search.addEventListener('input',renderProjects);document.querySelectorAll('.open-register').forEach(b=>b.onclick=()=>openForm('register'));document.querySelectorAll('.open-contact').forEach(b=>b.onclick=()=>openForm('contact'));document.getElementById('closeModal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const menuButton=document.getElementById('menuButton'),mainNav=document.getElementById('mainNav');menuButton.onclick=()=>{mainNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',mainNav.classList.contains('open'))};mainNav.querySelectorAll('a').forEach(a=>a.onclick=()=>mainNav.classList.remove('open'));
renderFilters();renderProjects();
